export const CREATE_NEW_EVENT_REQUEST = '@@editor/CREATE_NEW_EVENT_REQUEST';
export const CREATE_NEW_EVENT_SUCCESS = '@@editor/CREATE_NEW_EVENT_SUCCESS';
export const CREATE_NEW_EVENT_ERROR = '@@editor/CREATE_NEW_EVENT_ERROR';
