export const UNSUBSCRIBE_EVENT_REQUEST = '@@events/UNSUBSCRIBE_EVENT_REQUEST';
export const UNSUBSCRIBE_EVENT_REQUEST_SUCCESS = '@@events/UNSUBSCRIBE_EVENT_REQUEST_SUCCESS';
export const UNSUBSCRIBE_EVENT_REQUEST_ERROR = '@@events/UNSUBSCRIBE_EVENT_REQUEST_ERROR';
export const SUBSCRIBE_EVENT_REQUEST = '@@events/SUBSCRIBE_EVENT_REQUEST';
export const SUBSCRIBE_EVENT_REQUEST_SUCCESS = '@@events/SUBSCRIBE_EVENT_REQUEST_SUCCESS';
export const SUBSCRIBE_EVENT_REQUEST_ERROR = '@@events/SUBSCRIBE_EVENT_REQUEST_ERROR';