export const UNSUBSCRIBE_EVENT = '@@events/UNSUBSCRIBE_EVENT';
export const UNSUBSCRIBE_EVENT_SUCCESS = '@@events/UNSUBSCRIBE_EVENT_SUCCESS';
export const UNSUBSCRIBE_EVENT_ERROR = '@@events/UNSUBSCRIBE_EVENT_ERROR';
export const FETCH_EVENTS_REQUEST = '@@events/FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_SUCCESS = '@@events/FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_ERROR = '@@events/FETCH_EVENTS_ERROR';
