export const UNSUBSCRIBE_EVENT = '@@events/UNSUBSCRIBE_EVENT';
export const UNSUBSCRIBE_EVENT_SUCCESS = '@@events/UNSUBSCRIBE_EVENT_SUCCESS';
export const UNSUBSCRIBE_EVENT_ERROR = '@@events/UNSUBSCRIBE_EVENT_ERROR';